# Generated by Django 3.0.2 on 2020-12-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='Gender',
        ),
    ]
