# Generated by Django 3.0.2 on 2020-12-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201227_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
