# Generated by Django 3.0.2 on 2021-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('BeerSheba', 'BEERSHEBA'), ('TelAviv', 'TELAVIV')], default='BeerSheba', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=10),
        ),
    ]
