# Generated by Django 3.0.2 on 2020-12-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
