# Generated by Django 3.1.3 on 2021-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210102_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('BeerSheba', 'באר שבע'), ('TelAviv', 'תל אביב'), ('Ashdod', 'אשדוד'), ('Jerusalem', 'ירושלים'), ('Haifa', 'חיפה'), ('Jaffa', 'יפו'), ('Acre', 'עכו'), ('Nazareth', 'נצרת'), ('Lod', 'לוד'), ('Arad', 'ערד'), ('Dimona', 'דימונה'), ('Rishon Lezion', 'רישון לציון'), ('Ashkelon', 'אשקלון')], default='דימונה', max_length=40),
        ),
    ]
