# Generated by Django 3.1.3 on 2021-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210104_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'זכר'), ('Female', 'נקבה')], default='Male', max_length=10),
        ),
    ]
