# Generated by Django 3.0.2 on 2021-01-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
        ('core', '0006_auto_20210104_1125'),
    ]

    operations = [
    ]
