# Generated by Django 3.0.2 on 2021-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20210104_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.CharField(choices=[('טוב', 'מצוין'), ('בסדר', 'טוב מאוד'), ('בסדר', 'טוב מאוד')], default='מצוין', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[('BeerSheba', 'באר שבע'), ('TelAviv', 'תל אביב'), ('Ashdod', 'אשדוד'), ('Jerusalem', 'ירושלים'), ('Haifa', 'חיפה'), ('Jaffa', 'יפו'), ('Acre', 'עכו'), ('Nazareth', 'נצרת'), ('Lod', 'לוד'), ('Arad', 'ערד'), ('Dimona', 'דימונה'), ('Rishon Lezion', 'רישון לציון'), ('Ashkelon', 'אשקלון')], default='BeerSheba', max_length=40),
        ),
    ]
