# Generated by Django 3.0.2 on 2021-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210104_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.CharField(choices=[('good', 'טוב'), ('בסדר', 'טוב מאוד'), ('בסדר', 'טוב מאוד')], default='good', max_length=10),
        ),
    ]
