# Generated by Django 3.0.2 on 2021-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210104_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.CharField(choices=[('טוב', 'טוב'), ('בסדר', 'בסדר'), ('טוב מאוד', 'טוב מאוד'), ('לא טוב', 'לא טוב'), ('מצויין', 'מצויין')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_info',
            field=models.CharField(choices=[('זמין', 'זמין'), ('לא זמין', 'לא זמין')], default='זמין', max_length=10),
        ),
    ]
