# Generated by Django 3.0.2 on 2021-01-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_likes'),
        ('core', '0007_merge_20210104_1301'),
    ]

    operations = [
    ]
