# Generated by Django 3.0.2 on 2021-01-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20210106_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], default='זכר', max_length=10),
        ),
    ]
