# Generated by Django 3.0.2 on 2021-01-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210106_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urgent_request',
            new_name='UrgentRequest',
        ),
    ]
