# Generated by Django 3.0.2 on 2021-01-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210105_2137'),
        ('core', '0016_auto_20210106_1051'),
    ]

    operations = [
    ]
