# Generated by Django 3.0.2 on 2021-01-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20210107_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='urgentrequest',
            options={'verbose_name_plural': 'UrgentRequest'},
        ),
    ]
