# Generated by Django 3.0.2 on 2021-01-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210107_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgentrequest',
            name='email',
        ),
    ]
