# Generated by Django 3.1.3 on 2021-01-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='PageUpdate',
        ),
        migrations.AlterModelOptions(
            name='pageupdate',
            options={'verbose_name_plural': 'PageUpdate'},
        ),
    ]
