# Generated by Django 3.0.2 on 2021-01-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_urgentrequest_email'),
        ('core', '0019_auto_20210107_1456'),
    ]

    operations = [
    ]
