# Generated by Django 3.1.3 on 2021-01-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
