# Generated by Django 3.0.2 on 2021-01-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_site_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urgentrequest',
            old_name='name',
            new_name='שם',
        ),
        migrations.RemoveField(
            model_name='urgentrequest',
            name='subject',
        ),
    ]
