# Generated by Django 3.0.2 on 2021-01-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210109_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urgentrequest',
            old_name='שם',
            new_name='name',
        ),
    ]
