# Generated by Django 3.0.2 on 2021-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
    ]
